### ISSUE TITLE
Disabling Discord Rich Presence in the menu, and then attempting to open Discord while in-game, will insta-crash your game.

### ISSUE THREAD

**Issue by tobiasnchristensen** [restics/TelosAddon#2]
**The bug itself**
There's a new feature imbedded into the mod, focusing on Discord's 'Rich Presence'.

Disabling this feature, and then attempting to open Discord while in-game, will insta-crash your game, due to:

"java.lang.NullPointerException: Cannot invoke "com.jagrosh.discordipc.IPCClient.sendRichPresence(com.jagrosh.discordipc.entities.RichPresence)" because "this.client" is null"

**To Reproduce**
1. Join Telos Realms
2. Click on 'B, or whatever your menu keybind is for the mod'
3. Untick the Discord Rich Presence setting
4. Open Discord
5. See error (Insta-crash)

**Expected behavior**
Nothing in particular.

**Logs**
https://mclo.gs/vJUlYJs

**Additional context**
Nothing crazy, just a heads up - If you crash while in game, and while simultaneously opening Discord, this is likely why (if you're using the mod of course).

**Comment by restics** [comment]
was patched up already if u build from gh, once i fix the config bug ill push a new release
